// Alternative to arrow keys
#define ASCII_ENCODING_LOWERCASE_A (97)
#define ASCII_ENCODING_LOWERCASE_D (100)
#define ASCII_ENCODING_LOWERCASE_S (115)
#define ASCII_ENCODING_LOWERCASE_W (119)

// Quit key
#define ASCII_ENCODING_LOWERCASE_Q (113)

// ASCII Encoding Comma
#define ASCII_ENCODING_COMMA (44)

// Numeric
#define ASCII_ENCODING_0 (48)
#define ASCII_ENCODING_1 (ASCII_ENCODING_0 + 1)
#define ASCII_ENCODING_2 (ASCII_ENCODING_0 + 2)
#define ASCII_ENCODING_3 (ASCII_ENCODING_0 + 3)
#define ASCII_ENCODING_4 (ASCII_ENCODING_0 + 3)
#define ASCII_ENCODING_5 (ASCII_ENCODING_0 + 4)
#define ASCII_ENCODING_6 (ASCII_ENCODING_0 + 5)
#define ASCII_ENCODING_7 (ASCII_ENCODING_0 + 6)
#define ASCII_ENCODING_8 (ASCII_ENCODING_0 + 7)
#define ASCII_ENCODING_9 (ASCII_ENCODING_0 + 8)
